### ISSUE TITLE
A few suggestions for gendoc flag

### ISSUE THREAD

**Issue by shangsunset** [bww/hunit#1]
Just a few suggestions regarding to `gendoc` flag. 

1. If parent directory of the doc file path doesn't exist, create one instead of printing out an error.
2. Using test file name as doc file name when file name is not provided so that user doesn't need to provide a file name in a build file.

**Comment by bww** [comment]
Documentation is now generated as a separate output file for each input test suite under a specified root. For example, the input test suite `tests/foo.yml` produces the documentation file `docs/foo.md`, assuming the default documentation path `./docs`.

The `-gendoc` flag is now a boolean, an output path does not need to be provided. The following is valid and will produce an output doc file named `./docs/test.md`:

    hunit -gendoc test.yml

The output base directory can be specified with `-docpath`. The following will generate the file `./elsewhere/test.md`.

    hunit -gendoc -docpath ./elsewhere test.yml

The path to the document root is created if it doesn't already exist.
